//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam_150519_5_1
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Grades = new HashSet<Grade>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string HOURS { get; set; }
        public Nullable<decimal> AVG_GRADE { get; set; }
        public Nullable<int> NUM_OF_STUDENTS { get; set; }
        public Nullable<int> HIGHSET_GRADE { get; set; }
        [JsonIgnore]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
